CREATE TABLE `wp_term_taxonomy` (  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `taxonomy` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',  `count` bigint(20) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_taxonomy_id`),  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),  KEY `taxonomy` (`taxonomy`)) ENGINE=MyISAM AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_term_taxonomy` DISABLE KEYS */;
INSERT INTO `wp_term_taxonomy` VALUES('1', '1', 'category', '', '0', '7');
INSERT INTO `wp_term_taxonomy` VALUES('2', '2', 'link_category', '', '0', '7');
INSERT INTO `wp_term_taxonomy` VALUES('3', '3', 'nav_menu', '', '0', '38');
INSERT INTO `wp_term_taxonomy` VALUES('4', '4', 'nav_menu', '', '0', '6');
INSERT INTO `wp_term_taxonomy` VALUES('5', '5', 'nav_menu', '', '0', '4');
INSERT INTO `wp_term_taxonomy` VALUES('6', '6', 'nav_menu', '', '0', '6');
INSERT INTO `wp_term_taxonomy` VALUES('7', '7', 'faq-topic', '', '0', '3');
INSERT INTO `wp_term_taxonomy` VALUES('8', '8', 'faq-topic', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('9', '9', 'faq-topic', '', '0', '4');
INSERT INTO `wp_term_taxonomy` VALUES('10', '10', 'nav_menu', '', '0', '22');
INSERT INTO `wp_term_taxonomy` VALUES('11', '11', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('12', '12', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('13', '13', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('14', '14', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('15', '15', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('16', '16', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('17', '17', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('18', '18', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('19', '19', 'categories', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('20', '20', 'nav_menu', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('21', '21', 'category', '', '0', '27');
INSERT INTO `wp_term_taxonomy` VALUES('22', '22', 'category', '', '0', '19');
INSERT INTO `wp_term_taxonomy` VALUES('23', '23', 'category', '', '0', '9');
INSERT INTO `wp_term_taxonomy` VALUES('24', '24', 'category', '', '0', '63');
INSERT INTO `wp_term_taxonomy` VALUES('25', '25', 'category', '', '0', '42');
INSERT INTO `wp_term_taxonomy` VALUES('26', '26', 'category', 'Any Foods that have health benefits', '0', '93');
INSERT INTO `wp_term_taxonomy` VALUES('27', '27', 'category', '', '0', '17');
INSERT INTO `wp_term_taxonomy` VALUES('28', '28', 'category', '', '0', '99');
INSERT INTO `wp_term_taxonomy` VALUES('29', '29', 'category', '', '0', '83');
INSERT INTO `wp_term_taxonomy` VALUES('30', '30', 'category', 'This is where I can put any tips for safety that I might have.', '0', '42');
INSERT INTO `wp_term_taxonomy` VALUES('31', '31', 'category', 'This is testimonials that we receive from participants in Wellness.', '0', '12');
INSERT INTO `wp_term_taxonomy` VALUES('32', '32', 'faq-topic', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('33', '33', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('34', '34', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('35', '35', 'category', '', '0', '33');
INSERT INTO `wp_term_taxonomy` VALUES('36', '36', 'category', '', '0', '4');
INSERT INTO `wp_term_taxonomy` VALUES('37', '37', 'category', '', '0', '9');
INSERT INTO `wp_term_taxonomy` VALUES('38', '38', 'category', '', '0', '12');
INSERT INTO `wp_term_taxonomy` VALUES('39', '39', 'category', '', '0', '1');
INSERT INTO `wp_term_taxonomy` VALUES('40', '40', 'category', '', '0', '27');
INSERT INTO `wp_term_taxonomy` VALUES('41', '41', 'category', '', '0', '1');
/*!40000 ALTER TABLE `wp_term_taxonomy` ENABLE KEYS */;
